entWebDevProj/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.CustomLoginView.as_view(template_name='myapp/registration/login.html'), name='login'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('messages/', views.messages, name='messages'),
    path('', views.PostListView.as_view(), name='home'),
    path('addPost/', views.addPost, name='addPost'),
    path('badges/', views.badges, name='badges'),
    path('favorites/', views.favorites, name='favorites'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
]

myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Post(models.Model):
    username = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    category = models.CharField(max_length=10, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Indoor')
    tags = models.CharField(max_length=200, blank=True, null=True)
    is_flagged = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    favorites = models.ManyToManyField(User, related_name='favorited_posts', blank=True)
    like_count = models.IntegerField(default=0)  # New field for like count

    def update_like_count(self):
        self.like_count = self.likes.count()
        # self.save()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_logged_time = models.DateTimeField(null=True, blank=True)
    has_clicked_messages = models.BooleanField(default=False)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post
class SignUpForm(UserCreationForm):
    # email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'category', 'tags', 'is_flagged']
        widgets = {
            'title': forms.TextInput(attrs={'style': 'width: 800px;'}),     # Adjust width as needed
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 105}),  # Adjust rows and cols as needed
            'category': forms.RadioSelect(),
        }

myapp/views.py
import csv
import os
import sys
from datetime import datetime
import pytz
from django.db import connection
from django.shortcuts import render, redirect, get_object_or_404
from django.template import Context

from .models import Post
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.db.models import Q, Count
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from external_programs import user_profile

@login_required
def addPost(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.username = request.user.username
            post.save()
            return redirect('home')  # Change 'home' to your post listing page URL
    else:
        form = PostForm()
    return render(request, 'myapp/addPost.html', {'form': form})


@login_required
def messages(request):
    request.user.profile.has_clicked_messages = True
    request.user.profile.save()
    # new post message(s) logic
    user = request.user.profile
    posts_between_timestamps = Post.objects.filter(created_at__range=(user.last_logged_time, datetime.now(pytz.utc))).exclude(username=request.user)
    context = {'count': len(posts_between_timestamps), 'id': [], 'newposts': [], 'level': ""}
    # Suggestions logic:
    with connection.cursor() as cursor:
        # Execute a raw SQL query to select data from the suggestions table for the current user
        query = f"""SELECT * FROM suggestions WHERE user_id = {request.user.id}"""
        # print(query)
        cursor.execute(query)

        # Fetch all rows from the result set
        suggestions = cursor.fetchall()
        context['suggestions'] = suggestions
    for post in posts_between_timestamps:
        # if not post.username.__eq__(request.user):
        context['id'].append(post.id)
        context['newposts'].append({'id': post.id, 'message': "New Post: " + post.username + " posted about " + post.title})
    # Badge message logic
    count = Post.objects.filter(username=request.user).count()
    if count < 1:
        context['level'] = "You're " + str(1 - count) + (
            "post(s) away from unlocking Level 1! What are you waiting for? "
            "Post now")
    elif count < 3:
        context['level'] = "You're " + str(3 - count) + ("post(s) away from unlocking Level 2! What are you waiting "
                                                         "for?Post now")
    elif count < 6:
        context['level'] = "You're " + str(6 - count) + (
            "post(s) away from unlocking Level 3! What are you waiting for? "
            "Post now")
    elif count < 10:
        context['level'] = "You're " + str(10 - count) + (
            "post(s) away from unlocking Level 4! What are you waiting for? "
            "Post now")
    else:
        context['level'] = ("Message from Us: Thank you for being a amazing contributor. You have created 10+ "
                            "posts! Keep posting away!")
    return render(request, 'myapp/messages.html', context)


@login_required
def user_logout(request):
    # Update last_logged_out_time in  user Profile
    request.user.profile.has_clicked_messages = False
    request.user.profile.last_logged_time = datetime.now(pytz.utc)
    request.user.profile.save()
    logout(request)
    # Redirect to the home page or another page after logout
    return redirect('home')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # messages.success(request, 'Signup successful. Welcome!')
            return redirect('home')  # Change 'home' to your home page URL
        else:
            messages.error(request, 'Signup failed. Please correct the errors.')
    else:
        form = SignUpForm()
    random_posts = Post.objects.filter(is_flagged=False).order_by('?')[:3]  # Retrieve 3 random posts
    return render(request, 'myapp/registration/signup.html', {'form': form, 'random_posts': random_posts})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')  # Change 'home' to your home page URL
    else:
        form = AuthenticationForm()
    random_posts = Post.objects.filter(is_flagged=False).order_by('?')[:3]  # Retrieve 3 random posts
    return render(request, 'myapp/registration/login.html', {'form': form, 'random_posts': random_posts})


@login_required
def badges(request):
    count = Post.objects.filter(username=request.user).count()
    return render(request, 'myapp/badges.html', {'count': count})

@login_required
def favorites(request):
    favorite_posts = Post.objects.filter(favorites=request.user)
    return render(request, 'myapp/favorites.html', {'posts': favorite_posts})
@login_required
def dashboard(request):
    context = {}
    count = Post.objects.filter(username=request.user).count()
    most_posts_user = Post.objects.values('username').annotate(post_count=Count('id')).order_by('-post_count').first()
    print(most_posts_user['post_count'])
    context['count'] = count
    context['top'] = round(100 - 100*count/most_posts_user['post_count'], 2)
    if count < 1:
        context['level'] = 0
    elif count < 3:
        context['level'] = 1
    elif count < 6:
        context['level'] = 2
    elif count < 10:
        context['level'] = 3
    else:
        context['level'] = 4
    return render(request, 'myapp/dashboard.html', context)


class PostListView(LoginRequiredMixin, View):
    def get(self, request):
        query = request.GET.get('q')
        posts = self.sort_results(request, self.query_db(query))
        return render(request, 'myapp/home.html', {'posts': posts, 'query': query})

    def post(self, request):
        form = PostForm(request.POST)  # Create an instance of the form for handling tags
        if form.is_valid():
            post_id = request.POST.get('post_id')
            # print(form.cleaned_data['action'])
            if request.POST.get('action') == 'tag':
                tag = form.cleaned_data['tags']
                if tag and post_id:
                    try:
                        post = Post.objects.get(id=post_id)
                        if post.tags:
                            post.tags += tag.lower() + "; "
                        else:
                            post.tags = tag.lower() + '; '
                        post.save()
                    except Post.DoesNotExist:
                        pass
            elif request.POST.get('action') == 'flag':
                post = get_object_or_404(Post, pk=post_id)
                if not post.is_flagged:
                    post.is_flagged = True
                    post.save()
            elif request.POST.get('action') == 'like':
                post = get_object_or_404(Post, pk=post_id)
                post.likes.add(request.user)
                post.update_like_count()
                post.save()
            elif request.POST.get('action') == 'favorite':
                post = get_object_or_404(Post, pk=post_id)
                post.favorites.add(request.user)
                post.save()
        query = request.GET.get('q')
        posts = self.sort_results(request, self.query_db(query))
        return render(request, 'myapp/home.html', {'posts': posts, 'query': query})

    def query_db(self, query):
        if query:
            posts = Post.objects.filter(
                Q(username__icontains=query) |
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(tags__icontains=query)
            )
        else:
            # posts = Post.objects.all().order_by('-like_count') # TODO: sort on basis of user profile
            posts = Post.objects.all()
        return posts

    def read_user_profile(self, request):
        try:
            filename = sys.path[0] + "/user_profiles/user_profile_" + str(request.user.id) + ".csv"
            word_average_dict = {}
            with open(filename, mode='r') as file:
                csv_reader  = csv.DictReader(file, delimiter=',')
                for row in csv_reader:
                    if len(row) == 2:
                        word = row['Word'].strip().lower()
                        average = float(row['Average'])
                        word_average_dict[word] = average
            return word_average_dict
        except:
            pass
    def sort_results(self, request, posts):
        post_scores = []
        for post in posts:
            score = 0.0
            keywords = user_profile.clean_text(post.title)
            for keyword in keywords.split(' '):
                profile_dict = self.read_user_profile(request)
                if profile_dict:
                    score += profile_dict.get(keyword, 0.0)
            post_scores.append((post, score, post.like_count))
        # Sort the list of tuples based on scores in decreasing order
        sorted_post_scores = sorted(post_scores, key=lambda x: (x[1], x[2]), reverse=True)

        # Extract the sorted posts from the sorted tuples
        sorted_posts = [post for post, _, _ in sorted_post_scores]

        return sorted_posts
class CustomLoginView(LoginView):
    def get(self, request, *args, **kwargs):

templates/myapp/addPost.html
{#{% extends 'myapp/base.html' %}#}
{##}
{#{% block title %}Create Post - PetsBook{% endblock %}#}
{##}
{#{% block header %}Create Post - PetsBook{% endblock %}#}
{##}
{#{% block content %}#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Create Post</button>#}
{#    </form>#}
{#{% endblock %}#}

{% extends 'myapp/base.html' %}

{% block title %}Create Post - PetsBook{% endblock %}

{% block header %}Create Post - PetsBook{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_title">Title:</label>
            {{ form.title }}
        </p>
        <p>
            <label for="id_description">Description:</label>
            {{ form.description }}
        </p>
        <p>
            <label for="{{ form.category.id_for_label }}">Category:</label>
            {% for radio in form.category %}
                    {{ radio }}
            {% endfor %}
        </p>
        <button type="submit">Create Post</button>
    </form>
{% endblock %}

templates/myapp/badges.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block title %}Badges - PetsBook{% endblock %}

{% block header %}Your Badges{% endblock %}

{% block content %}
    <div  class="image-item">
        {% if count >= 1 %}
            <div class="gray-overlay" style="background-color: rgba(0, 0, 0, 0);">
                <img src="{% static 'level1.jpeg' %}" alt="Level 1" width="100" height="100" style="filter: grayscale(0%);">
                <label style="color: #000"><b>Level 1: </b><br>You created your first post!<br>Kitty says Hiii</label>
            </div>
        {% else %}
            <div class="gray-overlay">
                <img src="{% static 'level1.jpeg' %}" alt="Level 1" width="100" height="100">
                <label><b>Level 1: </b><br>You created your first post!<br>Kitty says Hiii</label>
            </div>
        {% endif %}
    </div>



    <div class="image-item">
        {% if count >= 3%}
            <div class="gray-overlay" style="background-color: rgba(0, 0, 0, 0);">
                <img src="{% static 'level2.jpeg' %}" alt="Level 2" width="100" height="100" style="filter: grayscale(0%);">
                <label style="color: #000"><b>Level 2: </b><br>You are on a streak with 3+ posts!<br>Alright! You got Mr. P's attention</label>
            </div>
        {% else %}
            <div class="gray-overlay">
                <img src="{% static 'level2.jpeg' %}" alt="Level 2" width="100" height="100">
                <label><b>Level 2: </b><br>You are on a streak with 3+ posts!<br>Alright! You got Mr. P's attention</label>
            </div>
        {% endif %}
    </div>
    <div class="image-item">
        {% if count >= 6%}
            <div class="gray-overlay" style="background-color: rgba(0, 0, 0, 0);">
                <img src="{% static 'level3.jpeg' %}" alt="Level 3" width="100" height="100" style="filter: grayscale(0%);">
                <label style="color: #000"><b>Level 3: </b><br>We love your contributions to PetsBook, you made 6+ posts<br>Charlie & Kitty sends &#10084; whauff &#10084; your way</label>
            </div>
        {% else %}
            <div class="gray-overlay">
                <img src="{% static 'level3.jpeg' %}" alt="Level 3" width="100" height="100">
                <label><b>Level 3: </b><br>We love your contributions to PetsBook, you made 6+ posts<br>Charlie & Kitty sends &#10084; whauff &#10084; your way</label>
            </div>
        {% endif %}
    </div>
    <div class="image-item">
        {% if count >= 10%}
            <div class="gray-overlay" style="background-color: rgba(0, 0, 0, 0);">
                <img src="{% static 'level4.jpeg' %}" alt="Level 4" width="100" height="100" style="filter: grayscale(0%);">
                <label style="color: #000"><b>Level 4: </b><br>Congrats you made 10+ posts!<br>Whoaaa our pet family RESPECTS your dedication</label>
            </div>
        {% else %}
            <div class="gray-overlay">
                <img src="{% static 'level4.jpeg' %}" alt="Level 4" width="100" height="100">
                <label><b>Level 4: </b><br>Congrats you made 10+ posts!<br>Whoaaa our pet family RESPECTS your dedication</label>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PetsBook{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<header>
    <img src="{% static 'pets_home.jpg' %}" alt="PetsBook Image" width="150" height="100">
    <h1>{% block header %}Welcome to PetsBook{% endblock %}</h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li>
                <div id="notification-icon">
                    <a href="{% url 'messages' %}">Message(s)</a>
                    <span id="notification-circle" {% if user.profile.has_clicked_messages %}style="display: none;"{% endif %}></span>
                </div>
                </li>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'addPost' %}">New Post</a></li>
                <li><a href="{% url 'badges' %}">Badges</a></li>
                <li><a href="{% url 'favorites' %}">Favorites</a></li>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li>Existing PetsBooker? <a href="{% url 'login' %}">Login</a></li>
                <li>New to PetsBook? <a href="{% url 'signup' %}">Sign up</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

<main>
    {% block content %}{% endblock %}
</main>

<footer>
    <p>&copy; 2023 PetsBook - author: Sreemoyee</p>
</footer>
</body>
</html>

templates/myapp/dashboard.html
{% extends 'myapp/base.html' %}

{% block title %}Dashboard - PetsBook{% endblock %}

{% block header %}Your Stats{% endblock %}

{% block content %}
    <h2>Dashboard</h2>

    <div class="dashboard-metrics">
        <div class="metric">
            <h3>Level</h3>
            <p class="metric-value">{{ level }}</p>
        </div>

        <div class="metric">
            <h3>Posts</h3>
            <p class="metric-value">{{ count }}</p>
        </div>

        <div class="metric">
            <h3>Based on your activity you're in the top</h3>
            {% if top == 0 %}
            <p class="metric-value">1%</p>
            {% else %}
                <p class="metric-value">{{ top }}%</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/myapp/favorites.html
{% extends 'myapp/base.html' %}
{% load custom_filters %}
{% block title %}Favorites - PetsBook{% endblock %}

{% block header %}Your Favorites, {{ user.username }}{% endblock %}

{% block content %}
{% if posts %}
    {% for post in posts %}
        <h3><a href="/#{{ post.id }}"   >{{ post.title }}</a></h3>
        <p>{{ post.description }}</p>
        <p>Category: {{ post.category }}</p>
        {% if user.username != post.username  %}
            <p>Author: {{ post.username }}</p>
        {% else %}
            <p>Author: You</p>
        {% endif %}
        {% if post.tags %}
            {% for tag in post.tags|split_tags %}
                {% if tag %}
                    <div id="tag-style">{{ tag }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
            <hr>
    {% endfor %}
    {% else %}
        <p>You haven't marked any posts as favorites yet.</p>
    {% endif %}
{% endblock %}

templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% load custom_filters %}
{% block title %}Home - PetsBook{% endblock %}

{% block header %}Welcome to PetsBook, {{ user.username }}{% endblock %}

{% block content %}
    <form method="get">
        <input id="search-bar" type="text" name="q" value="{{ query|default:'' }}" placeholder="Search">
        <button type="submit">Search</button>
    </form>

    {% if query %}
        <h2>Search results for '{{ query }}'</h2>
    {% endif %}
    {% for post in posts %}
        <h3><a id={{ post.id }}>{{ post.title }}</a></h3>
        <p>{{ post.description }}</p>
        <p>Category: {{ post.category }}</p>
        {% if user.username != post.username  %}
            <p>Author: {{ post.username }}</p>
            <form method="post">
                {% csrf_token %}
                <!-- Like button -->
                {% if user in post.likes.all %}
{#                    <button type="submit" name="action" value="unlike">Unlike</button>#}
                    <label style="color: blue">Liked</label>
                {% else %}
                    <button type="submit" name="action" value="like">Like</button>
                {% endif %}
                <!-- Favorite button -->
                {% if user in post.favorites.all %}
                    <label style="color: gold; background-color: red">Favorited</label>
                {% else %}
                    <button type="submit" name="action" value="favorite">Favorite</button>
                {% endif %}


                {% if not post.is_flagged %}
                    <button type="submit" name="action" value="flag">Flag</button>
                {% else %}
                    <label style="color: red">Flagged</label>
                {% endif %}
                <input type="hidden" name="post_id" value="{{ post.id }}">
                <input type="hidden" name="title" value="{{ post.title }}">
                <input type="hidden" name="description" value="{{ post.description }}">
                <input type="hidden" name="category" value="{{ post.category }}">
                <input type="text" name="tags" placeholder="Tag this post">
                <button type="submit" name="action" value="tag">Add Tag</button>
            </form>
        {% else %}
            <p>Author: You</p>
        {% endif %}
        {% if post.tags %}
            {% for tag in post.tags|split_tags %}
                {% if tag %}
                    <div id="tag-style">{{ tag }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

templates/myapp/messages.html
{% extends 'myapp/base.html' %}

{% block header %}Welcome to PetsBook, {{ user.username }}{% endblock %}

{% block content %}
    <h3>Here's what happened since you left</h3>
    <a href="/addPost">{{ level }}</a><br><br>
    {% if count > 0 %}
        {% for post in newposts %}
                <a href="/#{{ post.id }}">{{ post.message }}</a><br><br>
        {% endfor %}
    {% endif %}
    {% if suggestions %}
    {% for suggestion in suggestions %}
        <a href="/#{{ suggestion.2 }}">Here's some related content you might like: {{ suggestion.3 }}</a><br><br>
    {% endfor %}
    {% endif %}
{% endblock %}